import {
  getSeasons,
  getSeasonStats,
  getConfigValue,
} from "../../actions/serverRequests"
import SeasonWeeksHandler from "../../components/SeasonWeeksHandler"

export const metadata = {
  title: "Pick6 - Season",
  description: "Generated by create next app",
}

export default async function Season(): Promise<JSX.Element> {
  const currentSeason = await getConfigValue("CURRENT_SEASON")
  const seasons = await getSeasons()
  const seasonStats = await getSeasonStats(currentSeason, "asc", ["rank"])
  const seasonID = seasons.find(
    (season) => season.season_number == currentSeason
  )?.season_id
  const columnWidths = {
    rank: { small: 30, medium: 60, large: 50 },
    gp: { small: 30, medium: 60, large: 150 },
    group_number: { small: 30, medium: 60, large: 150 },
    win_percentage: { small: 30, medium: 60, large: 150 },
    won: { small: 30, medium: 60, large: 150 },
    played: { small: 55, medium: 60, large: 150 },
    player_name: { small: 105, medium: 160, large: 150 },
  }
  return (
    <div className="absolute top-0 left-[50px] w-[calc(100%-50px)] min-h-full flex flex-col text-center items-center overflow-x-hidden">
      <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl mt-1">
        Season Stats
      </h1>
      {seasons.length > 0 ? (
        <SeasonWeeksHandler
          currentSeason={currentSeason}
          currentWeek={undefined}
          selectedId={seasonID}
          selectOptions={seasons}
          initialData={seasonStats}
          headers={["Rank", "#", "GP", "Player", "Won", "Played", "%"]}
          columnWidths={columnWidths}
        />
      ) : (
        <h3 className="text-red-500">no data</h3>
      )}
    </div>
  )
}
