import { getSeasons, getSeasonStats } from "../../actions/serverRequests";
import SeasonWeeksHandler from "../../components/SeasonWeeksHandler"

export const metadata = {
    title: "Pick6 - Season",
    description: "Generated by create next app",
}

export default async function Season() {
    const currentSeason = process.env.CURRENT_SEASON
    const seasons = await getSeasons()
    const seasonStats = await getSeasonStats(currentSeason)
    const seasonID = seasons.find(season => season.season_number == currentSeason)?.season_id
    return (
        <div id="container">
            <h1>Pick6 - Season</h1>
            <h1>Season {currentSeason}</h1>
            <SeasonWeeksHandler
            currentSeason={currentSeason}
            selectedId={seasonID}
            selectOptions={seasons}
            initialData={seasonStats}
            headers={["Rank", "#", "GP", "Player", "Won", "Played", "%"]}
            />
        </div>
    )
}