import "../public/css/globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import { getSession } from "../lib/session";
import SessionTimeout from "../components/SessionTimeout";

export const metadata = {
  title: "Pick6 - Login",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession()
  return (
    <html lang="en">
      <body>
        {
          session ?
            <>
              <Navbar />
              <div id="content">
                <Sidebar sessionType={session?.user?.type}/>
                {children}
              </div>
              <SessionTimeout />
            </>
            : children
        }
      </body>
    </html>
  );
}
