import "./globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import Navbar from "../components/Navbar"
import Sidebar from "../components/Sidebar"
import { getSession } from "../lib/session"

export const metadata = {
  title: "Pick6 - Login",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }): Promise<JSX.Element> {
  const session = await getSession()
  return (
    <html lang="en">
      <body className="m-0 font-sans has-showing:overflow-hidden">
        <Navbar />
        <div
          id="content"
          className="min-h-[calc(100vh-50px)] absolute top-[50px] left-0 w-full flex flex-col items-center justify-center"
        >
          <Sidebar sessionType={session?.user?.type} />
          {children}
        </div>
      </body>
    </html>
  )
}
