import { getWeeks, getPicks } from "../../actions/serverRequests";
import SeasonWeeksHandler from "../../components/SeasonWeeksHandler";

export const metadata = {
    title: "Pick6 - Weekly",
    description: "Generated by create next app",
}

export default async function Weekly() {
    const currentSeason = process.env.CURRENT_SEASON
    const currentWeek = process.env.CURRENT_WEEK
    const weeks = await getWeeks()
    const weekID = weeks.find(week => week.season_number == currentSeason && week.week_number == currentWeek)?.week_id
    const picks = await getPicks(currentSeason, currentWeek)
    return (
        <div id="container">
            <h1>Pick6 - All Picks</h1>
            <SeasonWeeksHandler
            currentSeason={currentSeason}
            currentWeek={currentWeek}
            selectedId={weekID}
            selectOptions={weeks}
            initialData={picks.picks}
            headers={picks.headers}
            />
        </div>
    )
}