import { getWeeks, getPicks } from "../../actions/serverRequests";
import WeeksHandler from "../../components/WeeksHandler"

export const metadata = {
    title: "Pick6 - Weekly",
    description: "Generated by create next app",
}

export default async function Weekly() {
    const currentSeason = process.env.CURRENT_SEASON
    const currentWeek = process.env.CURRENT_WEEK
    const weeks = []//await getWeeks()
    const weekID = weeks.find(week => week.season_number == currentSeason && week.week_number == currentWeek)?.week_id
    const picks = []//await getPicks(currentSeason, currentWeek)
    return (
        <div id="container">
            <h1>Pick6 - All Picks</h1>
            <WeeksHandler 
            currentSeason={currentSeason}
            currentWeek={currentWeek}
            currentWeekID={weekID}
            allWeeks={weeks}
            weekPicks={picks.picks}
            headers={picks.headers}
            />
        </div>

    )
}