import ProfileHandler from "../../../components/ProfileHandler"
import { getUser, getProfilePictureURL } from "../../../actions/serverRequests"
import Image from "next/image"

export const metadata = {
  title: "Pick6 - Profile Viewer",
  description: "Generated by create next app",
}

export default async function profileID({ params }): Promise<JSX.Element> {
  const user = await getUser(params.id)
  const profilePicURL = await getProfilePictureURL()
  return (
    <div className="absolute top-0 left-[50px] w-[calc(100%-50px)] min-h-full flex flex-col text-center items-center overflow-x-hidden">
      <div className="relative ml-auto mr-auto w-[200px] h-[200px]">
        <Image
          key={Date.now()}
          className="absolute top-0 left-0 h-full w-full bg-[#bbb] bg-cover rounded-[50%]"
          src={profilePicURL ? profilePicURL : `/default.png`}
          priority
          width={"200"}
          height={"200"}
          alt="profile_picture"
        />
      </div>
      <ProfileHandler id={params.id} />
    </div>
  )
}
