import ProfileHandler from "../../../components/ProfileHandler"
import { getUser, getProfilePictureURL } from "../../../actions/serverRequests";
import Image from "next/image";

export const metadata = {
    title: "Pick6 - Profile Viewer",
    description: "Generated by create next app",
};

export default async function profileID({ params }) {
    const user = await getUser(params.id)
    const profilePicURL = undefined//await getProfilePictureURL()
    return (
        <div id="container">
            <div id="profile_picture_container">
                <Image key={Date.now()} id="circle" src={profilePicURL ? profilePicURL : `/img/default.png`} priority width={"200"} height={"200"} alt="profile_picture"/>
            </div>
            <ProfileHandler id={params.id} />
        </div>
    )
}