import { getWeekGames, isTimerPaused, calculateTimeUntilReset } from "../../actions/serverRequests";
import TeamsHandler from "../../components/TeamsHandler"

export const metadata = {
    title: "Pick6 - Teams",
    description: "Generated by create next app",
}

export default async function Teams() {
    const currentSeason = process.env.CURRENT_SEASON
    const currentWeek = process.env.CURRENT_WEEK
    const weekGames = []//await getWeekGames(currentSeason, currentWeek)
    const timerPaused = await isTimerPaused()
    const timerTime = await calculateTimeUntilReset()
    return (
        <div id="container">
            <h1>Pick6 - Select Teams</h1>
            <h1>Week {currentWeek} of Season {currentSeason}</h1>
            <TeamsHandler 
            weekGames={weekGames}
            timerPaused={timerPaused}
            timerTime={timerTime}
            currentSeason={currentSeason}
            currentWeek={currentWeek}
            />
        </div>
    )
}