import SessionTimeout from "../../components/SessionTimeout"

export const metadata = {
    title: "Pick6 - Admin Guide",
    description: "Generated by create next app",
};

export default function AdminGuide(): JSX.Element {
    return (
        <>
            <h1>Pick6 - Admin Guide</h1>
            <ol style={{ textAlign: "center", listStylePosition: "inside", maxWidth: "900px" }}>
                <li>If you would like to create new users select Insert User(s). From a csv/text file the format is (user,password,gp,type,group_number) per line.</li>
                <li>If you would like to delete users select Delete User(s). From a csv/text file the format is each user seperated by a commma. Checking hard delete deletes their data soft delete only prevents them from logging in.</li>
                <li>To pause/unpause the timer select the Toggle Timer option</li>
                <li>Before any seasons/weeks can be created select Set Week/Season option and enter your desired start season and week.</li>
                <li>To upload games ensure the timer is paused and convert the games sheet from histo check.xlsm to a csv file. Select Upload Games option and select the csv file.</li>
                <li>Enter the desired time to set the timer to for players to make picks see <a href="https://www.npmjs.com/package/ms" target="_blank">format</a> for formats and type the raw text without ms.</li>
                <li>To upload picks ensure the timer is unpaused and convert the picks sheet from histo check.xlsm to a csv file. Select Upload Picks option and select the csv file.</li>
                <li>To process the game scores and winners/losers ensure the timer is paused. Then convert the games sheet from histo check.xlsm to a csv file. Select Enter Winners option and select the csv file. The week number will be advanced automatically after this process.</li>
                <li>Repeat steps 6-8 each week.</li>
            </ol>
            <SessionTimeout />
        </>
    )
}