import AdminUtilityHandler from "../../components/AdminUtilityHandler"

export const metadata = {
    title: "Pick6 - Admin Utility",
    description: "Generated by create next app",
}

export default async function AdminUtility() {
    const season = process.env.CURRENT_SEASON
    const week = process.env.CURRENT_WEEK
    const timerStatus = process.env.TIMER_PAUSED === "1" ? "Paused" : "Unpaused"
    const timerResetTime = new Date(Number(process.env.TARGET_RESET_TIME)).toLocaleString()
    return (
        <div id="container">
            <AdminUtilityHandler season={season} week={week} timerStatus={timerStatus} resetTime={timerResetTime} />
        </div>

    )
}