import { getConfigValue } from "../../actions/serverRequests"
import AdminUtilityHandler from "../../components/AdminUtilityHandler"
import SessionTimeout from "../../components/SessionTimeout"

export const metadata = {
  title: "Pick6 - Admin Utility",
  description: "Generated by create next app",
}

export default async function AdminUtility(): Promise<JSX.Element> {
  const season = await getConfigValue("CURRENT_SEASON")
  const week = await getConfigValue("CURRENT_WEEK")
  const timerStatus =
    (await getConfigValue("TIMER_PAUSED")) === "1" ? "Paused" : "Unpaused"
  const timerResetTime = new Date(
    Number(await getConfigValue("TARGET_RESET_TIME"))
  ).toLocaleString()
  return (
    <div className="absolute top-0 left-[50px] w-[calc(100%-50px)] h-full overflow-auto flex flex-col text-center items-center overflow-x-hidden">
      <AdminUtilityHandler
        season={season ? season : "N/A"}
        week={week ? week : "N/A"}
        timerStatus={timerStatus}
        resetTime={timerResetTime}
      />
      <SessionTimeout />
    </div>
  )
}
